### PR TITLE
Feature/book and pages

### PR DESCRIPTION
**Pull request by BenSinger2005**
OOH THAT UP SMASH

HAPPY FEET
WOMBO COMBO

### CODE REVIEW

**Review by ankitbisain — COMMENTED** [review]
upvote

**Review by ankitbisain — APPROVED** [review]
T'HAT A'INT F'ALCO

**Comment by BenSinger2005** [comment]
OOOH OHHH OOHHHHH

OHHH MY GOD

WHERE YOU AT
WHERE YOU AT

OHHH
OH MY GOD
WOMBO COMBO

OH 
GET YO BUTT WHOOPED

**Review by EricrPark — APPROVED** [review]

**Review by ankitbisain — COMMENTED** [review]
T'HAT A'INT F'ALCO

**Pull request merged**
